sudo: false

language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "nightly"

addons:
    apt:
        packages:
            - gdb

install:
    - git clone https://github.com/stedolan/jq.git
    - (cd jq
        && autoreconf -i
        && ./configure --disable-maintainer-mode
        && make -j8 CFLAGS="-O0 -g" LDFLAGS=-rdynamic)

script:
    - python jv_printer_test.py

notifications:
    email: false
